import logging
from datetime import date
from pathlib import Path
from typing import Optional

from google import genai
from google.genai import types

from config import GEMINI_API_KEY, GEMINI_MODEL

logger = logging.getLogger(__name__)

_MOM_PROMPT_TEMPLATE = """\
You are an expert meeting facilitator and business analyst. Produce a professional \
Minutes of Meeting (MoM) document in Markdown from the transcript below.

Meeting details:
- Title: {title}
- Date: {date}
- Participants: {participants}

Full transcript:
{transcript}

Generate the MoM using EXACTLY this structure (do not add or rename sections):

# Minutes of Meeting: {title}

**Date:** {date}
**Duration:** Estimated from transcript content
**Participants:** {participants}
**Meeting type:** [Determine from context, e.g., Project Review, Standup, Strategy, Client Call]

## Executive Summary
[2-4 sentence overview of what was discussed and decided]

## Agenda Items Discussed
1. **[Topic]** — [brief description]
2. **[Topic]** — [brief description]
(add as many as needed)

## Key Decisions
- [Decision] — Owner: [Name or Team]
(add as many as needed)

## Action Items

| # | Action | Owner | Due Date | Priority |
|---|--------|-------|----------|----------|
| 1 | [action] | [owner] | [date or TBD] | High/Medium/Low |
(add as many rows as needed)

## Key Discussion Points
[Bullet points summarising important discussions, debates, or clarifications]

## Next Steps
[Numbered list of immediate follow-up actions]

## Next Meeting
[Date/time if mentioned, otherwise "To be scheduled"]

---
*Generated by Botverse AI Scribe · Powered by Gemini 1.5 Flash (free) · {date}*

Rules:
- Use only information from the transcript; do not invent facts.
- If a field cannot be determined from the transcript, write "Not specified".
- Output Markdown only — no preamble, no commentary outside the document.
"""

_EMPTY_MOM_TEMPLATE = """\
# Minutes of Meeting: {title}

**Date:** {date}
**Duration:** N/A
**Participants:** {participants}
**Meeting type:** N/A

## Executive Summary
No speech was detected during this recording session. The audio may have been silent, \
or the meeting may not have contained audible conversation.

## Agenda Items Discussed
- No content recorded.

## Key Decisions
- No decisions recorded.

## Action Items

| # | Action | Owner | Due Date | Priority |
|---|--------|-------|----------|----------|
| — | No action items recorded | — | — | — |

## Key Discussion Points
No discussion points recorded.

## Next Steps
- Review recording setup and retry if audio was expected.

## Next Meeting
To be scheduled.

---
*Generated by Botverse AI Scribe · Powered by Gemini 1.5 Flash (free) · {date}*
"""


class MoMGenerator:
    def __init__(self) -> None:
        if not GEMINI_API_KEY:
            raise ValueError("GEMINI_API_KEY is not set.")
        self._client = genai.Client(api_key=GEMINI_API_KEY)

    # ------------------------------------------------------------------

    def generate(
        self,
        transcript: str,
        meeting_title: str = "Teams Meeting",
        participants: Optional[list[str]] = None,
    ) -> str:
        today = date.today().strftime("%B %d, %Y")
        participant_str = ", ".join(participants) if participants else "Not recorded"

        if not transcript or not transcript.strip():
            logger.info("Transcript is empty — returning minimal MoM")
            return _EMPTY_MOM_TEMPLATE.format(
                title=meeting_title,
                date=today,
                participants=participant_str,
            )

        prompt = _MOM_PROMPT_TEMPLATE.format(
            title=meeting_title,
            date=today,
            participants=participant_str,
            transcript=transcript,
        )

        logger.info("Generating MoM with Gemini (transcript length: %d chars)…", len(transcript))
        try:
            response = self._client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(temperature=0.2),
            )
            mom_text = response.text.strip() if response.text else ""
            if not mom_text:
                raise ValueError("Gemini returned an empty MoM response")
            logger.info("MoM generated (%d chars)", len(mom_text))
            return mom_text
        except Exception as exc:
            logger.error("MoM generation failed: %s", exc)
            return _EMPTY_MOM_TEMPLATE.format(
                title=meeting_title,
                date=today,
                participants=participant_str,
            )

    def save(self, mom_text: str, output_path: str) -> None:
        Path(output_path).write_text(mom_text, encoding="utf-8")
        logger.info("MoM saved to %s", output_path)
