import logging
from datetime import date
from pathlib import Path
from typing import Optional

from google import genai
from google.genai import types

from config import GEMINI_API_KEY, GEMINI_MODEL

logger = logging.getLogger(__name__)

_MOM_PROMPT_TEMPLATE = """\
You are an expert meeting facilitator and business analyst. Produce a professional \
Minutes of Meeting (MoM) document in Markdown from the transcript below.

Meeting details:
- Title: {title}
- Date: {date}
- Participants: {participants}

Full transcript:
{transcript}

Generate the MoM using EXACTLY this structure (do not add or rename sections):

# Minutes of Meeting: {title}

**Date:** {date}
**Duration:** Estimated from transcript content
**Participants:** {participants}
**Meeting type:** [Determine from context, e.g., Project Review, Standup, Strategy, Client Call]

## Executive Summary
[2-4 sentence overview of what was discussed and decided]

## Agenda Items Discussed
1. **[Topic]** — [brief description]
2. **[Topic]** — [brief description]
(add as many as needed)

## Key Decisions
- [Decision] — Owner: [Name or Team]
(add as many as needed)

## Action Items

| # | Action | Owner | Due Date | Priority |
|---|--------|-------|----------|----------|
| 1 | [action] | [owner] | [date or TBD] | High/Medium/Low |
(add as many rows as needed)

## Key Discussion Points
[Bullet points summarising important discussions, debates, or clarifications]

## Next Steps
[Numbered list of immediate follow-up actions]

## Next Meeting
[Date/time if mentioned, otherwise "To be scheduled"]

---
*Generated by Protiviti AI Scribe · Powered by Gemini 2.5 Flash (free) · {date}*

Rules:
- Use only information from the transcript; do not invent facts.
- If a field cannot be determined from the transcript, write "Not specified".
- Output Markdown only — no preamble, no commentary outside the document.
"""

_EMPTY_MOM_TEMPLATE = """\
# Minutes of Meeting: {title}

**Date:** {date}
**Duration:** N/A
**Participants:** {participants}
**Meeting type:** N/A

## Executive Summary
No speech was detected during this recording session. The audio may have been silent, \
or the meeting may not have contained audible conversation.

## Agenda Items Discussed
- No content recorded.

## Key Decisions
- No decisions recorded.

## Action Items

| # | Action | Owner | Due Date | Priority |
|---|--------|-------|----------|----------|
| — | No action items recorded | — | — | — |

## Key Discussion Points
No discussion points recorded.

## Next Steps
- Review recording setup and retry if audio was expected.

## Next Meeting
To be scheduled.

---
*Generated by Protiviti AI Scribe · Powered by Gemini 2.5 Flash (free) · {date}*
"""


class MoMGenerator:
    def __init__(self) -> None:
        if not GEMINI_API_KEY:
            raise ValueError("GEMINI_API_KEY is not set.")
        self._client = genai.Client(api_key=GEMINI_API_KEY)

    # ------------------------------------------------------------------

    def generate(
        self,
        transcript: str,
        meeting_title: str = "Teams Meeting",
        participants: Optional[list[str]] = None,
    ) -> str:
        today = date.today().strftime("%B %d, %Y")
        participant_str = ", ".join(participants) if participants else "Not recorded"

        if not transcript or not transcript.strip():
            logger.info("Transcript is empty — returning minimal MoM")
            return _EMPTY_MOM_TEMPLATE.format(
                title=meeting_title,
                date=today,
                participants=participant_str,
            )

        prompt = _MOM_PROMPT_TEMPLATE.format(
            title=meeting_title,
            date=today,
            participants=participant_str,
            transcript=transcript,
        )

        logger.info("Generating MoM with Gemini (transcript length: %d chars)…", len(transcript))
        try:
            response = self._client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(temperature=0.2),
            )
            mom_text = response.text.strip() if response.text else ""
            if not mom_text:
                raise ValueError("Gemini returned an empty MoM response")
            logger.info("MoM generated (%d chars)", len(mom_text))
            return mom_text
        except Exception as exc:
            logger.error("MoM generation failed: %s", exc)
            return _EMPTY_MOM_TEMPLATE.format(
                title=meeting_title,
                date=today,
                participants=participant_str,
            )

    def save(self, mom_text: str, output_path: str) -> None:
        Path(output_path).write_text(mom_text, encoding="utf-8")
        logger.info("MoM saved to %s", output_path)

    @staticmethod
    def format_for_teams_chat_html(mom_text: str, meeting_title: str) -> str:
        """Convert the full MoM markdown into an HTML message for Graph API chat posting."""
        import re

        def extract_section(text: str, heading: str) -> str:
            pattern = rf"## {re.escape(heading)}\n(.*?)(?=\n## |\Z)"
            m = re.search(pattern, text, re.DOTALL)
            return m.group(1).strip() if m else ""

        def esc(s: str) -> str:
            return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

        today = date.today().strftime("%B %d, %Y")
        summary = extract_section(mom_text, "Executive Summary")
        decisions = extract_section(mom_text, "Key Decisions")
        next_steps = extract_section(mom_text, "Next Steps")

        # Pull action item rows from the markdown table
        action_rows: list[tuple[str, str, str]] = []
        in_table = False
        for line in mom_text.splitlines():
            if "| # | Action |" in line:
                in_table = True
                continue
            if in_table:
                if not line.startswith("|"):
                    break
                if re.match(r"\|\s*[-:]+", line):
                    continue
                cols = [c.strip() for c in line.split("|")[1:-1]]
                if len(cols) >= 4 and cols[1] and cols[1] != "—":
                    action_rows.append((cols[1], cols[2], cols[3]))

        html = [
            f"<h2>📋 Minutes of Meeting: {esc(meeting_title)}</h2>",
            f"<p><em>{today} · Generated by Protiviti AI Scribe</em></p>",
        ]

        if summary:
            html.append(f"<p><strong>Executive Summary</strong><br>{esc(summary)}</p>")

        if decisions:
            html.append("<p><strong>Key Decisions</strong></p><ul>")
            for line in decisions.splitlines():
                stripped = line.strip().lstrip("-").strip()
                if stripped:
                    html.append(f"<li>{esc(stripped)}</li>")
            html.append("</ul>")

        if action_rows:
            html.append("<p><strong>Action Items</strong></p><ul>")
            for action, owner, due in action_rows:
                html.append(f"<li>{esc(action)} — {esc(owner)} (due {esc(due)})</li>")
            html.append("</ul>")

        if next_steps:
            html.append(f"<p><strong>Next Steps</strong><br>{esc(next_steps)}</p>")

        html.append("<p><em>Full MoM saved in the meeting_output folder.</em></p>")

        return "".join(html)
